### PR TITLE
Cloud Wallpaper

### PR DESCRIPTION
**Pull request by matteodev8**

### CODE REVIEW

**Comment by omaemae** [comment]
could you include some shadow of sorts around the CyberOS logo and, if possible, attach source files?

**Comment by matteodev8** [comment]
> 
> 
> could you include some shadow of sorts around the CyberOS logo and, if possible, attach source files?

I can make the shadow and wdym by source files? Do you mean the default Image without the Cyber Logo?

**Comment by omaemae** [comment]
> > could you include some shadow of sorts around the CyberOS logo and, if possible, attach source files?
> 
> I can make the shadow and wdym by source files? Do you mean the default Image without the Cyber Logo?

what software did you use for the image?

**Comment by matteodev8** [comment]
> 
> 
> > > could you include some shadow of sorts around the CyberOS logo and, if possible, attach source files?
> > 
> > 
> > I can make the shadow and wdym by source files? Do you mean the default Image without the Cyber Logo?
> 
> what software did you use for the image?

GIMP 2.10 and shot on an iPhone SE 2020

**Comment by omaemae** [comment]
> > > > could you include some shadow of sorts around the CyberOS logo and, if possible, attach source files?
> > > 
> > > 
> > > I can make the shadow and wdym by source files? Do you mean the default Image without the Cyber Logo?
> > 
> > 
> > what software did you use for the image?
> 
> GIMP 2.10 and shot on an iPhone SE 2020

could you include the .xcf and the original photo in a new directory in `matteodev/`?

**Comment by matteodev8** [comment]
> 
> 
> > > > > could you include some shadow of sorts around the CyberOS logo and, if possible, attach source files?
> > > > 
> > > > 
> > > > I can make the shadow and wdym by source files? Do you mean the default Image without the Cyber Logo?
> > > 
> > > 
> > > what software did you use for the image?
> > 
> > 
> > GIMP 2.10 and shot on an iPhone SE 2020
> 
> could you include the .xcf and the original photo in a new directory in `matteodev/`?

Yes

**Comment by matteodev8** [comment]
Done

**Comment by matteodev8** [comment]
Okay Now Its fixed

**Pull request merged**
